/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assigment4;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author Adam Sykes
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    // Add a mouse listener to the DrawPanel
    public void addMouseListenerToDrawPanel(MouseListener listener) {
        drawPanel.addMouseListener(listener);
    }
    
    // Add a mouse motion listener to the DrawPanel
    public void addMouseMotionListenerToDrawPanel(MouseMotionListener listener) {
        drawPanel.addMouseMotionListener(listener);
    }
    
    public JToggleButton getToggleButton(){
        return addToggleButton;
    }
    public JToggleButton getCToggleButton(){
        return addcToggleButton;
    }
    public void addUndoButtonListener(ActionListener al){
        undo.addActionListener(al);
    }
    public void addRedoButtonListener(ActionListener al){
        redo.addActionListener(al);
    }
    public void addMenuUndoListener(ActionListener al){
        MenuUndo.addActionListener(al);
    }
    public void addMenuExitListener(ActionListener al){
        MenuExit.addActionListener(al);
    }
    public void addMenuRedoListener(ActionListener al){
        MenuRedo.addActionListener(al);
    }
    // Add an action listener to the Toggle Button
    public void addToggleButtonListener(ActionListener al){
        addToggleButton.addActionListener(al);
    }
    public void addCToggleButtonListener(ActionListener al){
        addcToggleButton.addActionListener(al);
    }
    // Returns true if the "Add Rectangle" button is selected
    public boolean addRectangleButtonIsSelected() {
        return addToggleButton.isSelected();
    }
    
    public DrawPanel getDrawPanel() {
        return drawPanel;
    }
    
    public JTable getRectangleTable() {
        return rectangleTable;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new assigment4.DrawPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectangleTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        addToggleButton = new javax.swing.JToggleButton();
        addcToggleButton = new javax.swing.JToggleButton();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuUndo = new javax.swing.JMenuItem();
        MenuRedo = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        rectangleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shape", "Position (X,Y)", "Width", "Height"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rectangleTable);
        if (rectangleTable.getColumnModel().getColumnCount() > 0) {
            rectangleTable.getColumnModel().getColumn(0).setResizable(false);
            rectangleTable.getColumnModel().getColumn(1).setResizable(false);
            rectangleTable.getColumnModel().getColumn(2).setResizable(false);
            rectangleTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jToolBar1.setRollover(true);

        addToggleButton.setText("Add Rectangle");
        jToolBar1.add(addToggleButton);

        addcToggleButton.setText("Add Circle");
        jToolBar1.add(addcToggleButton);

        undo.setText("Undo");
        jToolBar1.add(undo);

        redo.setText("Redo");
        jToolBar1.add(redo);

        jMenu1.setText("File");

        MenuUndo.setText("Undo");
        jMenu1.add(MenuUndo);

        MenuRedo.setText("Redo");
        jMenu1.add(MenuRedo);

        MenuExit.setText("Exit");
        jMenu1.add(MenuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
            .addComponent(drawPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuRedo;
    private javax.swing.JMenuItem MenuUndo;
    private javax.swing.JToggleButton addToggleButton;
    private javax.swing.JToggleButton addcToggleButton;
    private assigment4.DrawPanel drawPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable rectangleTable;
    private javax.swing.JButton redo;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}
